[tools]
lua = "latest"

[tasks.test]
run = "lua test/run.lua"

[tasks.install]
run = "sudo ln -sf ./bin/lasyd /usr/local/bin/lasyd"

[tasks.uninstall]
run = "sudo rm -f /usr/local/bin/lasyd"

[tasks.list]
run = "bin/lasyd list"

[tasks.help]
run = "bin/lasyd help"
